final : Node.o LinkedList.o ds-main.cpp
	g++ -g Node.o LinkedList.o ds-main.cpp -o final

Node.o : Node.cpp Node.h
	g++ -g -c Node.cpp -o Node.o

LinkedList.o : LinkedList.cpp LinkedList.h
	g++ -g -c LinkedList.cpp -o LinkedList.o

clean: 
	rm -rf *.o final
