All: Node.o LinkedList.o ds-main.cpp
  g++ Node.o LinkedList.o ds-main.cpp -o All

Node.o : Node.c Node.h
  g++ Node.c Node.h -o Node.o

LinkedList.o : LinkedList.c LinkedList.h
  g++ LinkedList.c LinkedList.h -o LinkedList.o
